apiVersion: k3d.io/v1alpha3
kind: Simple
name: k3d-registry
servers: 1
agents: 2
registries:
  create: 
    name: k3d-registry
  config: |
    mirrors:
      "localhost:5000":
        endpoint:
          - http://localhost:5000