apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.26.1 (a9d05d509)
  creationTimestamp: null
  labels:
    io.kompose.service: imageservice
  name: imageservice
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: imageservice
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml
        kompose.version: 1.26.1 (a9d05d509)
      creationTimestamp: null
      labels:
        io.kompose.service: imageservice
    spec:
      containers:
        - image: imageservice
          name: imageservice
          ports:
            - containerPort: 5003
          resources: {}
      restartPolicy: Always
status: {}
