kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
     name: local-disk
provisioner: Local
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mssql-data
  annotations:
    volume.beta.kubernetes.io/storage-class: local-disk
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi