apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: authenticationservice
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: authenticationservice
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50